version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./prisma:/app/prisma
