version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=chat_room_user
      - DB_PASSWORD=secure_password
      - DB_NAME=chat_room_db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=chat_room_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=chat_room_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
